"""Bazel rules for running Windows executables under Wine during testing.

Provides `wine_test`, `wine_rust_test`, and `wine_binary` macros that
wrap Rust and native Windows binaries with a Wine execution layer for
Linux CI.

The core Rust utilities for managing Wine process lifecycle (prefix
creation, process spawning, timeout, cleanup) live in
`//bazel/rules/testing/wine:sentinel_wine_test`.
"""

load("@rules_rust//rust:defs.bzl", "rust_test", "rust_binary", "rust_library")

def _wine_test_transition_impl(settings, attr):
    """Transition to a Windows target platform for Wine execution."""
    return {
        "//bazel/platforms:target_platform": "//bazel/platforms:windows_x86_64_release",
    }

_wine_test_transition = transition(
    implementation = _wine_test_transition_impl,
    inputs = [],
    outputs = ["//bazel/platforms:target_platform"],
)

def _wine_test_impl(ctx):
    """Run a prebuilt Windows executable under Wine.

    Manages setup, execution, and teardown of Wine processes:
    - Creates an isolated Wine prefix (WINEPREFIX) per invocation.
    - Spawns the Windows executable via `wine <exe>`.
    - Applies a configurable timeout.
    - Cleans up the prefix and kills wineserver on completion.
    """
    wine = ctx.executable._wine
    exe = ctx.file.windows_exe

    # Generate a shell script that invokes the Rust WineTest helper
    # or runs Wine directly with proper prefix management.
    out = ctx.actions.declare_file(ctx.label.name + ".sh")

    content = """#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Wine test wrapper — generated by wine_test.bzl
#
# Binary:  {exe}
# Prefix:  auto (temp dir, cleaned up on exit)
# Timeout: {timeout}
# ---------------------------------------------------------------------------
set -euo pipefail

WINE="{wine}"
EXE="{exe}"
TIMEOUT="{timeout}"

# Create an isolated Wine prefix
WINEPREFIX="$(mktemp -d "/tmp/wine_prefix_XXXXXX")"
export WINEPREFIX
export WINEDEBUG="-all"
export WINEARCH="win64"

cleanup() {{
    local ret=$?
    # Kill wineserver
    "$WINE" wineserver -k 2>/dev/null || true
    # Remove prefix
    rm -rf "$WINEPREFIX" 2>/dev/null || true
    exit $ret
}}
trap cleanup EXIT INT TERM

# Bootstrap the prefix
"$WINE" wineboot --init 2>/dev/null || {{ echo "Wine prefix init failed"; exit 1; }}

# Run the test binary
if [[ "$TIMEOUT" -gt 0 ]]; then
    timeout "$TIMEOUT" "$WINE" "$EXE" "$@" 2>&1
else
    "$WINE" "$EXE" "$@" 2>&1
fi
""".format(
        wine = wine.short_path,
        exe = exe.short_path,
        timeout = ctx.attr.timeout_seconds,
    )

    ctx.actions.write(out, content, is_executable = True)

    runfiles = ctx.runfiles(files = [wine, exe])
    return [DefaultInfo(executable = out, runfiles = runfiles)]

wine_test = rule(
    implementation = _wine_test_impl,
    attrs = {
        "windows_exe": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The Windows executable to run under Wine",
        ),
        "timeout_seconds": attr.int(
            default = 120,
            doc = "Per-test timeout in seconds (0 = no timeout)",
        ),
        "_wine": attr.label(
            default = "@wine_linux_x86_64//:wine",
            executable = True,
            cfg = "exec",
            doc = "The Wine binary (from http_archive dep)",
        ),
        "_allowlist_function_transition": attr.label(
            default = "@bazel_tools//tools/allowlists/function_transition_allowlist",
        ),
    },
    test = True,
    doc = """Run a Windows executable under Wine with isolated prefix management.

Creates a temporary WINEPREFIX, spawns the executable, waits for completion
with a configurable timeout, and cleans up both the prefix and wineserver
on exit.
""",
)

def wine_rust_test(name, windows_binary, timeout = 120, **kwargs):
    """Build a Rust Windows binary and wrap it in a Wine test.

    Args:
        name: The test name.
        windows_binary: Path to the Rust source file (crate_root) for the
                        Windows binary to compile.
        timeout: Per-test timeout in seconds (default 120).
        **kwargs: Additional arguments passed to rust_binary.
    """
    binary_name = name + "_windows_bin"

    # Build the Rust binary for Windows x86_64 via cross-compilation
    rust_binary(
        name = binary_name,
        crate_root = windows_binary,
        **kwargs
    )

    # Wrap it in a Wine test
    wine_test(
        name = name,
        windows_exe = ":" + binary_name,
        timeout_seconds = timeout,
    )

def windows_cross_test(name, **kwargs):
    """Convenience alias for cross-platform Wine tests.

    Identical to wine_rust_test. Use this when you want to clearly
    indicate that the test is a cross-compilation test.
    """
    wine_rust_test(name = name, **kwargs)
